name: dependency-review
on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  dependency-review:
    permissions:
      pull-requests: write
    uses: fish-shop/workflows/.github/workflows/dependency-review.yml@6a5908d44f6d627a36b6cb053f9e4dc4c9e38147 # v1.12.0
