name: dependency-review
on:
  pull_request:
    branches:
      - main
jobs:
  dependency-review:
    uses: fish-shop/workflows/.github/workflows/dependency-review.yml@87881b58a2286829a28c4053900560a2eeeed396 # v1.10.0
