name: dependency-review
on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  dependency-review:
    permissions:
      pull-requests: write
    uses: fish-shop/workflows/.github/workflows/dependency-review.yml@5f95f810f8716ed65452165bab6f3d89a606397e # v1.13.0
