name: markdown-links
on:
  pull_request:
    branches:
      - main
jobs:
  markdown-links:
    uses: fish-shop/workflows/.github/workflows/markdown-links.yml@87881b58a2286829a28c4053900560a2eeeed396 # v1.10.0
