name: release-tags
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  release-tags:
    uses: fish-shop/workflows/.github/workflows/release-tags.yml@87881b58a2286829a28c4053900560a2eeeed396 # v1.10.0
