name: release-tags
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions: read-all

jobs:
  release-tags:
    permissions:
      contents: write
    uses: fish-shop/workflows/.github/workflows/release-tags.yml@6a5908d44f6d627a36b6cb053f9e4dc4c9e38147 # v1.12.0
